# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

services:
  web:
    depends_on: [ mongo ]
    image: renewed-renaissance-storefront:latest
    environment:
      CANONICAL_URL: http://localhost:4000
      BUILD_GRAPHQL_URL: http://localhost:3000/graphql
      EXTERNAL_GRAPHQL_URL: http://localhost:3000/graphql
      INTERNAL_GRAPHQL_URL: http://localhost:3000/graphql
      SEGMENT_ANALYTICS_SKIP_MINIMIZE: true
      SEGMENT_ANALYTICS_WRITE_KEY: ENTER_KEY_HERE
      SESSION_MAX_AGE_MS: 2592000000
      SESSION_SECRET: CHANGEME
      STRIPE_PUBLIC_API_KEY: ENTER_STRIPE_PUBLIC_KEY_HERE
    ports:
      - 3000:3000
      - 4000:4000
      - 4080:4080

  mongo:
    image: mongo:5.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - /opt/renewed-renaissance/data/db:/data/db
    healthcheck: # re-run rs.initiate() after startup if it failed.
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
