# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:

services:
  web:
    image: renewed-renaissance-storefront:latest
    env_file: [ ./.env ]
    networks: [ reaction ]
    ports:
      - 4000:4000
  init:
    image: reaction-cli:latest
    env_file: [ ./.env ]
    entrypoint: [ /usr/local/bin/npx ]
    command: [ reaction create-project admin myadmin ]
    networks: [ reaction ]
