# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:

services:
  web:
    depends_on: [ mongo ]
    image: renewed-renaissance-storefront:latest
    env_file: [ ./.env ]
    networks: [ reaction ]
    ports:
      - 4000:4000
      - 4080:4080

  mongo:
    image: mongo:5.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks: [ reaction ]
    ports:
      - "27017:27017"
    volumes:
      - /opt/renewed-renaissance/data/db:/data/db
    healthcheck: # re-run rs.initiate() after startup if it failed.
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
